### ISSUE TITLE
Release Checklist: v0.9.0-rc-r.3

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1005]
**Catalogs:**
- [x] Use helm3 in script installation
- [x] Provide script for helm2 and helm3 in chart installtion

**Addons:**
- [x] Fix flags (Int32) + Revendor
- [x] Fix weight in front matter.

**Stash operator:**
- [x] helm 3 should be first tab
- [x] Remove script installation procedure.  Replace with `helm template` and `kubectl apply`

**Comment by tamalsaha** [comment]
- [ ] Mark v1alpha1 deprecated.

**Comment by hossainemruz** [comment]
Not relevant anymore.
