### ISSUE TITLE
Stash v0.10.0-rc.0 release tracker

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#1119]
Issue To Fix:
- [ ] [kubectl-stash download broken](https://github.com/stashed/stash/issues/1110)
- [ ] [Single BackupBatch makes stash think Repository does not exist](https://github.com/stashed/stash/issues/1113)
- [ ] Fix wait logic for thedatabase to be ready
  - [x] MySQL
  - [ ] PostgreSQL
  - [ ] Elasticsearch
  - [ ] MongoDB
  - [ ] Percona-XtraDB
 
Features:
- [ ] Apply SecretTransform to allow to use custom secret
   - [ ] MySQL
   - [ ] PostgreSQL
   - [ ] Elasticsearch
   - [ ] Percona-XtraDB
   - [ ] MongoDB

- [ ] Tag Stash addon's image with `-v1` suffix
- [ ] Update documentation
