### ISSUE TITLE
Tracking Issue: Release 0.9.0-rc.0

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#857]
**Operator:**
- [ ] Release `0.9.0-rc.0`
- [ ] Push chart
- [ ] Push docker image

**Docs:**
- [ ] Update setup doc
- [ ] Replace `0.8.3` with `0.9.0-rc.0`
- [ ] Update website

**Plugins:**

- Postgres:
	- [ ] Push `stash-postgres` chart
		- [ ] 11.2
		- [ ] 10.6
		- [ ] 10.2
		- [ ] 9.6
	- [ ] Push `stash-postgres` docker image
		- [ ] 11.2
		- [ ] 10.6
		- [ ] 10.2
		- [ ] 9.6
- MongoDB:
	- [ ] Push `stash-mongodb` chart
		- [ ] 4.1
		- [ ] 4.0
		- [ ] 3.6
		- [ ] 3.4
	- [ ] Push `stash-mongodb` docker image
		- [ ] 4.1
		- [ ] 4.0
		- [ ] 3.6
		- [ ] 3.4
- Elasticsearch:
	- [ ] Push `stash-elasticsearch` chart
		- [ ] 7.2
		- [ ] 6.8
		- [ ] 6.5
		- [ ] 6.4
		- [ ] 6.3
		- [ ] 6.2
		- [ ] 5.6
	- [ ] Push `stash-elasticsearch` docker image
		- [ ] 7.2
		- [ ] 6.8
		- [ ] 6.5
		- [ ] 6.4
		- [ ] 6.3
		- [ ] 6.2
		- [ ] 5.6
- MySQL:
 	- [ ] Push `stash-mysql` chart
		- [ ] 8.0.14
		- [ ] 5.7
	- [ ] Push `stash-mysql` docker image
		- [ ] 8.0.14
	 	- [ ] 5.7
