### ISSUE TITLE
Release Checklist: 0.9.0-rc.2

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#935]
**Step-1: Stash Operator**
- [x] Release Stash Operator
- [x] Publish Stash Docker Image
- [x] Update [stashed/installer](https://github.com/stashed/installer)
- [x] Release [stashed/installer](https://github.com/stashed/installer)
- [x] Publish Stash Chart

**Step-2: Stash Addons**
This step is required only if any change has been introduces since the last release or changes in Stash operator affect the addons.

- [x] Revendor addons repos with latest Stash release
- [x] Cherry-pick changes into all versions & re-tag
- [x] Update [stashed/catalog](https://github.com/stashed/catalog) (if required)
- [x] Release [stashed/catalog](https://github.com/stashed/catalog) (if required)
- [x] Publish Addon Charts
- [x] Publish Addon Docker Images

**Step-2: Stash kubectl plugin**

- [x] Revendor addons repos with latest Stash release
- [x] Publish cli binaries

**Step-3: Documentation**
- [x] Write Changelog in [stashed/docs](https://github.com/stashed/docs)
- [x] Release [stashed/docs](https://github.com/stashed/docs)

**Step-4: Website Update**
- [x] Update [appscode/static-assets](https://github.com/appscode/static-assets)
- [x] Render & Verify latest update locally in [appscode-cloud/hugo-appscode](https://github.com/appscode-cloud/hugo-appscode)
- [x] Publish Website

**Step-5: Announcement**
- [x] Write Release Notes
- [x] Announce new release
